version: "3"
services:
    mariadb:
        image: mariadb
        volumes:
            - data-volume:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=db"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=user"
            - "MYSQL_ROOT_PASSWORD=admin"
        ports:
            - "3306:3306"
volumes:
    data-volume:
